-----BEGIN CERTIFICATE-----
MIIEjzCCA3egAwIBAgIUANh+BPWJBjM57z9R0OIPRIOA1NkwDQYJKoZIhvcNAQELBQAweDELMAkG
A1UEBhMCVVMxEzARBgNVBAgMCkNhbGlmb3JuaWExEjAQBgNVBAcMCVBhbG8gQWx0bzEVMBMGA1UE
CgwMU2hhZG93cm9ja2V0MSkwJwYDVQQDDCBTaGFkb3dyb2NrZXQgMjAyMy0xMi0wMSAwMTo0NDoz
NjAeFw0yMzExMzAxODQ0MzZaFw0zMzExMjcxODQ0MzZaMHgxCzAJBgNVBAYTAlVTMRMwEQYDVQQI
DApDYWxpZm9ybmlhMRIwEAYDVQQHDAlQYWxvIEFsdG8xFTATBgNVBAoMDFNoYWRvd3JvY2tldDEp
MCcGA1UEAwwgU2hhZG93cm9ja2V0IDIwMjMtMTItMDEgMDE6NDQ6MzYwggEiMA0GCSqGSIb3DQEB
AQUAA4IBDwAwggEKAoIBAQDWxmWNTT1dF7zXjU9m+iRPQhhZ643hY5N5V3AYgxmzOAmNb4SHYohD
q65GhdmnkwnB0pj61rME3VBKn2aKZX7r75K8fq6jzohaZXUQvoienxgC9gCcpcPgLUtHpuXTV4kO
0PIYPNdnDj2as/Zh5u5nxN+KYKNtLR1nZDRYH+X+HypdAE7nGcFyFiPMpGSsGXgwJ/6FbRHZQiI2
oECIzNL7rh/KMpgnLbbKeSEN+1E+8QuBpvxDH0vazgEjh71Axa8vmBcMag6RDdN1Njg9/sm9n4EC
O+2Zi5nzG/CzF+YxHrYsLdb9CAN3dCuCpSRphGze8lbCMDk2YSOMXMBCu0ejAgMBAAGjggEPMIIB
CzAPBgNVHRMBAf8EBTADAQH/MA4GA1UdDwEB/wQEAwIBhjAdBgNVHQ4EFgQUuhu+H5M5h2vG/iYU
AcDqiwK7BBEwgbUGA1UdIwSBrTCBqoAUuhu+H5M5h2vG/iYUAcDqiwK7BBGhfKR6MHgxCzAJBgNV
BAYTAlVTMRMwEQYDVQQIDApDYWxpZm9ybmlhMRIwEAYDVQQHDAlQYWxvIEFsdG8xFTATBgNVBAoM
DFNoYWRvd3JvY2tldDEpMCcGA1UEAwwgU2hhZG93cm9ja2V0IDIwMjMtMTItMDEgMDE6NDQ6MzaC
FADYfgT1iQYzOe8/UdDiD0SDgNTZMBEGCWCGSAGG+EIBAQQEAwICBDANBgkqhkiG9w0BAQsFAAOC
AQEAlGavvVqcPgUQ+o2VGix7mPJXK+KUkhsW7CRQ0insQy78R9ahZvjlSTQsGeu+7v2MSoT9ZcMc
OwwejpUPS6NsDSMOJrFGflew/ASVHkfxJXsV+kT1i1I894hyQaJQIGrtIRo6z0nMm6Myfo6TAGcO
lZ1q5soBgm8Lv9J5TvymCJ+b/Q0V3rDr05N487o4xXuQfouYaCpfn3eDCklam5d/a3Sz49NjoT5u
iulIuqw8343/FxUB53k9O+dNSTmfWnA3dpoQ+6gGBsLHzwG6OqtiN2/p5Hcaoscd7Cf4roSef5wu
PrqqjbCJECBmpWk22K9Gp5zRcpKjsPq7q/hkqg9R5w==
-----END CERTIFICATE-----
